export default [
  { id: 1, text: 'Know more about Web Accessibility', link: 'https://medium.freecodecamp.org/pragmatic-rules-of-web-accessibility-that-will-stick-to-your-mind-9d3eb85a1a28' },
  { id: 2, text: 'Do you first open source contribution', link: 'https://medium.freecodecamp.org/how-to-make-your-first-open-source-contribution-in-just-5-minutes-aaad1fc59c9a' },
  { id: 3, text: 'Clean up your PC or Phone' },
  { id: 4, text: 'Clean up your inbox' },
  { id: 5, text: 'Learn Express.js', link: 'https://expressjs.com/' },
  { id: 6, text: 'Learn to greet someone in a new language' },
  { id: 7, text: 'Learn Vue' },
  { id: 8, text: 'Learn React' },
  { id: 9, text: 'Learn how to play a new sport' },
  { id: 10, text: "Text a friend you haven't talked to in a long time" },
  { id: 11, text: 'Learn a new programming language' },
  { id: 12, text: 'Learn how to fold a paper crane' },
  { id: 13, text: 'Find a DIY to do' },
  { id: 14, text: 'Learn about the Golden Ratio', link: 'https://en.wikipedia.org/wiki/Golden_ratio' },
  { id: 15, text: 'Volunteer at a local animal shelter' },
  { id: 16, text: 'Play a game of Monopoly' },
  { id: 17, text: 'Bake pastries for you and your neighbor' },
  { id: 18, text: "Bake something you've never tried before" },
  { id: 19, text: 'Take your dog on a walk' },
  { id: 20, text: 'Meditate for five minutes' },
  { id: 21, text: "Start a book you've never gotten around to reading" },
  { id: 22, text: 'Take a caffeine nap' },
  { id: 23, text: 'Take a bubble bath' },
  { id: 24, text: 'Go to a nail salon' },
  { id: 25, text: 'Listen to your favorite album' },
  { id: 26, text: 'Learn to play a new instrument' },
  { id: 27, text: 'Teach your dog a new trick' },
  { id: 28, text: 'Make a to-do list for your week' },
  { id: 29, text: 'Go swimming with a friend' },
  { id: 30, text: 'Go on a long drive' },
  { id: 31, text: "Watch a movie you'd never usually watch" },
  { id: 32, text: 'Go see a movie in theaters with a few friends' },
  { id: 33, text: 'Draw and color a Mandala' },
  { id: 34, text: 'Rearrange and organize your room' },
  { id: 35, text: 'Pot some plants and put them around your house' },
  { id: 36, text: "Plan a vacation you've always wanted to take" },
  { id: 37, text: 'Take your cat on a walk' },
  { id: 38, text: 'Have a football scrimmage with some friends' },
  { id: 39, text: 'Fill out a basketball bracket' },
  { id: 40, text: 'Play a game of tennis with a friend' },
  { id: 41, text: 'Catch up with a friend over a lunch date' },
  { id: 42, text: 'Learn how to iceskate or rollerskate' },
  { id: 43, text: 'Go to a concert with local artists with some friends' },
  { id: 44, text: 'Explore the nightlife of your city' },
  { id: 45, text: "Fix something that's broken in your house" },
  { id: 46, text: 'Wash your car' },
  { id: 47, text: 'Hold a yard sale' },
  { id: 48, text: 'Donate blood at a local blood center', link: 'https://www.redcross.org/give-blood' },
  { id: 49, text: 'Volunteer and help out at a senior center' },
  { id: 50, text: 'Shop at support your local farmers market' },
  { id: 51, text: 'Learn a new recipe' },
  { id: 52, text: 'Create a cookbook with your favorite recipes' },
  { id: 53, text: 'Volunteer at your local food shelter' },
  { id: 54, text: 'Create or update your resume' },
  { id: 55, text: 'Paint the first thing you see' },
  { id: 56, text: "Start a blog for something you're passionate about" },
  { id: 57, text: 'Start a garden' },
  { id: 58, text: "Clean out your closet and donate the clothes you've outgrown" },
  { id: 59, text: 'Catch up on world news' },
  { id: 60, text: 'Create a personal website' },
  { id: 61, text: 'Listen to a new podcast' },
  { id: 62, text: 'Have a paper airplane contest with some friends' },
  { id: 63, text: 'Learn calligraphy' },
  { id: 64, text: 'Start a collection' },
  { id: 65, text: 'Go to a local thrift shop' },
  { id: 66, text: 'Make a couch fort' },
  { id: 67, text: 'Pick up litter around your favorite park' },
  { id: 68, text: 'Buy a new house decoration' },
  { id: 69, text: 'Write a thank you letter to an influential person in your life' },
  { id: 70, text: 'Clean out your car' },
  { id: 71, text: 'Write a short story' },
  { id: 72, text: 'Do something nice for someone you care about' },
  { id: 73, text: 'Think of a new business idea' },
  { id: 74, text: 'Clean out your garage' },
  { id: 75, text: 'Learn to sew on a button' },
  { id: 76, text: 'Learn how to french braid hair' },
  { id: 77, text: 'Learn how to whistle with your fingers' },
  { id: 78, text: 'Learn to write with your nondominant hand' },
  { id: 79, text: 'Make bread from scratch' },
  { id: 80, text: 'Make a budget' },
  { id: 81, text: 'Make a simple musical instrument' },
  { id: 82, text: 'Go to the gym' },
  { id: 83, text: "Try a food you don't like" },
  { id: 84, text: 'Conquer one of your fears' },
  { id: 85, text: 'Go to a concert with some friends' },
  { id: 86, text: 'Go to the library and find an interesting book' },
  { id: 87, text: 'Go to an escape room' },
  { id: 88, text: 'Go to a karaoke bar with some friends' },
  { id: 89, text: 'Repaint a room in your house' },
  { id: 90, text: 'Pull a harmless prank on one of your friends' },
  { id: 91, text: 'Take a spontaneous road trip with some friends' },
  { id: 92, text: 'Go stargazing' },
  { id: 93, text: 'Invite some friends over for a game night' },
  { id: 94, text: 'Make homemade ice cream' },
  { id: 95, text: 'Start a daily journal' },
  { id: 96, text: 'Go to a music festival with some friends' },
  { id: 97, text: 'Make a bucket list' },
  { id: 98, text: 'Binge watch a trending series' },
  { id: 99, text: 'Learn how to make a website' },
  { id: 100, text: 'Create and follow a savings plan' },
  { id: 101, text: 'Watch a classic movie' },
  { id: 102, text: 'Plan a trip to another country' },
  { id: 103, text: 'Learn how the internet works' },
  { id: 104, text: 'Take a hike at a local park' },
  { id: 105, text: 'Make tie dye shirts' },
  { id: 106, text: 'Make a scrapbook with pictures of your favorite memories' },
  { id: 107, text: 'Have a picnic with some friends' },
  { id: 108, text: 'Have a bonfire with your close friends' },
  { id: 109, text: 'Memorize the fifty states and their capitals' },
  { id: 110, text: 'Take a class of something that interests you' },
  { id: 111, text: "Resolve a problem you've been putting off" },
  { id: 112, text: 'Make a new friend' },
  { id: 113, text: 'Take a nap' },
  { id: 114, text: 'Learn a new language' },
  { id: 115, text: 'Go to the gym' },
  { id: 116, text: 'Brush your teeth' },
  { id: 117, text: 'Drink some water' },
  { id: 118, text: 'Make a tea' },
  { id: 119, text: 'Fork this app and learn something in the process' },
  { id: 120, text: 'Go for a bike ride' },
  { id: 121, text: 'Build a spaceship' },
  { id: 122, text: 'Draw a horse' },
  { id: 123, text: 'People watch' },
  { id: 124, text: 'Go day - drinking' },
  { id: 125, text: 'Play chess' },
  { id: 126, text: 'Start a random game of Tag with a stranger' },
  { id: 127, text: 'Play 2048 mobile game' },
  { id: 128, text: 'Make a list of things to do and then take a nap' },
  { id: 129, text: 'Learn to skateboard' },
  { id: 130, text: 'Look through the GitHub repo 👀' },
  { id: 131, text: 'Go for a walk ' },
  { id: 132, text: 'Netflix and chill' },
  { id: 133, text: 'Give bullet journaling a try' },
  { id: 134, text: 'Go for a run!' },
  { id: 135, text: 'Go do that dance.' },
  { id: 136, text: 'Take a shit' },
  { id: 137, text: 'Put down your phone and hang out with your closest person near you.' },
  { id: 138, text: 'Clip your toe nails' },
  { id: 139, text: 'Walk for 30 mins' },
  { id: 140, text: 'Meditate for 10 mins' },
  { id: 141, text: 'Call your mother' },
  { id: 142, text: 'Drink whiskey!' },
  { id: 143, text: 'Take an online course' },
  { id: 144, text: 'Pick your nose' },
  { id: 145, text: 'Dance with yourself!' },
  { id: 146, text: 'Learn React' },
  { id: 147, text: 'Play an Escape Room' },
  { id: 148, text: 'Go skating' },
  { id: 149, text: 'Go for a walk in Chinatown' },
  { id: 150, text: 'Take A Shower' },
  { id: 151, text: 'Meditate' },
  { id: 152, text: 'Learn About Islam' },
  { id: 153, text: 'Learn Magic Tricks' },
  { id: 154, text: 'Drink Mezcal' },
  { id: 155, text: 'Brew your own kombucha' },
  { id: 156, text: 'Invite a stranger that you see often out for a coffee' },
  { id: 157, text: 'Call Mom' },
  { id: 158, text: 'Re-organize your library' },
  { id: 159, text: 'Clean out the refrigerator' },
  { id: 160, text: 'Clean up your wardrobe' },
  { id: 161, text: 'Leave the house and walk without a destination in mind for 15 minutes and decide where to go on crossroads' },
  { id: 162, text: 'Learn five colours in French' },
  { id: 163, text: 'Put on moisturizer' },
  { id: 164, text: 'Do a plank' },
  { id: 165, text: 'Do 10 squads' },
  { id: 166, text: "Revisit Your New Year's Resolutions" },
  { id: 167, text: 'Make a smoothie' },
  { id: 168, text: 'Grab some boba with friends!' },
  { id: 169, text: 'Sing a Song' },
  { id: 170, text: 'Take a bus till the last stop and then explore that neighborhood' },
  { id: 171, text: 'Go outside and mark your territory' },
  { id: 172, text: 'Clean your room' },
  { id: 173, text: 'Yoga' },
  { id: 174, text: 'Draw something!' },
  { id: 175, text: 'When will you code' },
  { id: 176, text: 'Play Zelda' },
  { id: 177, text: 'Play Chess' },
  { id: 178, text: 'Go for a swim' },
  { id: 179, text: 'Do some writing' },
  { id: 180, text: 'Leave Facebook' },
  { id: 181, text: "Make a plan to surprise a friend with something they'd like" }
]